name: Build

on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Swift Package
    strategy:
      matrix:
        os: ["macos-latest"]
        swift: ["5.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full history

      - name: List Repository Files
        run: ls -R  # Lists all files and directories to confirm the project's presence

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      
      - name: Get Swift version
        run: swift --version

      - name: Build Swift Package
        run: swift build -c release  # Builds the Swift package in release mode

      - name: Archive Build Products
        run: |
          mkdir -p output
          cp -R .build/release/* output/

      - name: Upload Build Products as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TUSKit_Build_Products
          path: output
