name: Build TUSKit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # Updated to latest version

    - name: Build TUSKit
      run: |
        xcodebuild clean -project TUSKit.xcodeproj -scheme TUSKit -configuration Release -sdk iphonesimulator -arch x86_64 build  # Added `clean` for fresh builds

    - name: Archive TUSKit Framework
      run: |
        set -e  # Stop on error
        mkdir -p output
        cp -R build/Release-iphonesimulator/TUSKit.framework output/

    - name: Upload TUSKit Framework
      uses: actions/upload-artifact@v2
      with:
        name: TUSKit.framework
        path: output/TUSKit.framework
