name: Build

on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Framework
    strategy:
      matrix:
        os: ["macos-latest"]
        swift: ["5.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full history

      - name: List Repository Files
        run: ls -R  # Lists all files and directories to confirm the project's presence

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      
      - name: Get Swift version
        run: swift --version

      - name: Generate Xcode Project
        run: swift package generate-xcodeproj  # Generates TUSKit.xcodeproj from the Swift package

      - name: List Available Schemes
        run: xcodebuild -list -project TUSKit.xcodeproj  # Verifies the generated project and lists schemes

      - name: Build Framework
        run: |
          xcodebuild clean build \
          -scheme TUSKit \
          -configuration Release \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" \
          -derivedDataPath build

      - name: Archive Framework
        run: |
          mkdir -p output
          find build -name "TUSKit.framework" -exec cp -R {} output/ \;

      - name: Upload Framework as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TUSKit.framework
          path: output/TUSKit.framework
