name: Build TUSKit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4  # Updated to the latest version

    - name: Build TUSKit
      run: |
        xcodebuild clean -project TUSKit.xcodeproj -scheme TUSKit -configuration Release -sdk iphonesimulator -arch x86_64 build

    - name: Archive TUSKit Framework
      run: |
        mkdir -p output
        cp -R build/Release-iphonesimulator/TUSKit.framework output/

    - name: Upload TUSKit Framework
      uses: actions/upload-artifact@v4  # Updated to the latest version
      with:
        name: TUSKit.framework
        path: output/TUSKit.framework
