name: Build

on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Swift Package with Objective-C Wrapper
    strategy:
      matrix:
        os: ["macos-latest"]
        swift: ["5.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full history

      - name: List Repository Files
        run: ls -R  # Lists all files and directories to confirm the project's presence

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      
      - name: Get Swift version
        run: swift --version

      - name: Build for iOS Device (arm64)
        run: |
          swift build --configuration release --arch arm64 --triple arm64-apple-ios --build-path .build/ios-arm64
          
      - name: Build for iOS Simulator (x86_64)
        run: |
          swift build --configuration release --arch x86_64 --triple x86_64-apple-ios --build-path .build/ios-x86_64

      - name: Create Objective-C Wrapper
        run: |
          mkdir -p Wrapper
          cat <<EOF > Wrapper/TUSKitWrapper.h
          #import <Foundation/Foundation.h>

          @interface TUSKitWrapper : NSObject
          - (NSString *)exampleFunction;
          @end
          EOF

          cat <<EOF > Wrapper/TUSKitWrapper.m
          #import "TUSKitWrapper.h"
          @import TUSKit;  // Import TUSKit module

          @implementation TUSKitWrapper

          - (NSString *)exampleFunction {
              // Example Swift function wrapped in Objective-C
              return [TUSKit someSwiftFunction];  // Replace with actual Swift call
          }

          @end
          EOF

      - name: Create XCFramework
        run: |
          xcodebuild -create-xcframework \
            -framework .build/ios-arm64/Release/TUSKit.framework \
            -framework .build/ios-x86_64/Release/TUSKit.framework \
            -output output/TUSKit.xcframework

      - name: Upload XCFramework as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TUSKit_XCFramework
          path: output/TUSKit.xcframework
